// src/components/Projects/data.ts
import { Project } from './types';

export const projects: Project[] = [
  {
    id: 1,
    abbr: "Castaway",
    color: "bg-blue-900",
    badge: "APP",
    title: "Castaway",
    subtitle: "비언어적 감정 케어 서비스",
    date: "2025.10.31 ~ 12.08",
    team: "4명",
    role: "프로젝트 총괄 ─ 프로젝트 기획 및 AI·서비스 구조 설계 및 FE/BE 개발",
    tags: ["React Native", "FastAPI", "NLP"],
    desc: "사용자의 일기를 분석해 감정을 추출하고,\n그 감정에 맞는 섬의 날씨와 BGM, 오브제를\n생성하는 비언어적 힐링 서비스입니다.",
    overview: "일기 텍스트에서 감정을 분석하여 시각(섬 날씨, 오브제)과 청각(BGM)으로 표현하는 멀티모달 힐링 앱입니다. 사용자의 감정 리듬을 시각화하여 직관적인 피드백을 제공합니다. 또한 클러스터링을 통해 감정 패턴이 유사한 사용자들끼리 경험을 공유할 수 있습니다.",
    features: [
      "NLP 감정 분석 (RoBERTa 기반)",
      "감정 결과에 따른 3D 오브제 및 BGM 생성",
      "감정 리듬 예측 및 주간 리포트 생성",
      "사용자별 감정 패턴 공유"
    ],
    stack: ["React Native", "Node.js", "Python", "FastAPI", "PostgreSQL", "AWS"],
    performance: "비언어적 감정 표현 중심 감정 분석 정확도 93% 달성",
    hasVideo: true,
    githubUrl: "https://github.com/kjw402540/castaway.git",
    githubUrl2: "https://github.com/kjw402540/castaway_AI.git",
    videoId: "j26ylkr2T80?si=92XZf4JgeDaKQ1sQ",
  },
  {
    id: 2,
    abbr: "ZipPT",
    color: "bg-emerald-800",
    badge: "WEB",
    title: "집PT",
    subtitle: "자연어 처리 기반 주거 추천 플랫폼",
    date: "25.04.14 ~ 05.21 / 25.07.01 ~ 08.01",
    team: "6명",
    role: "프로젝트 총괄 ─ 전체 아키텍처 & 로직 구성, FE/BE 개발",
    tags: ["Flask", "Data Analysis", "KoELECTRA"],
    desc: "사용자가 원하는 주거 조건을 자연어로 입력하면, 공공 데이터를 분석하여 최적의 동네를 추천하고 시각화된 리포트를 제공합니다.",
    overview: "공공 데이터를 활용해 사용자의 자연어 요구사항(e.g: '역세권이고 조용한 곳')을 분석하고, 점수화 로직을 통해 최적의 주거지를 추천해주는 웹 서비스입니다. 지도 기반 시각화와 상세 리포트를 통해 사용자가 쉽게 정보를 탐색할 수 있도록 설계되었습니다.",
    features: [
      "자연어 요구사항 분석 (KoELECTRA)",
      "주거 환경 점수화 알고리즘",
      "지도 기반 데이터 시각화 (Kakao Map API)",
      "동네별 상세 리포트 제공"
    ],
    stack: ["JavaScript", "Python", "Flask", "MySQL", "OpenAI API"],
    performance: "기능별 모듈화를 통해 6인 팀 병렬 개발 환경 구축 및 충돌 최소화",
    hasVideo: true,
    githubUrl: "https://github.com/kingdonghae/aicc-second",
    videoId: "2UAp9rwh5Zw",
    videoId2: "6lBBcElBsIk",
  },
  {
    id: 3,
    abbr: "QA",
    color: "bg-indigo-800",
    badge: "AI CORE",
    title: "RLHF QA Bot",
    subtitle: "인간 피드백 기반 질의응답 모델",
    date: "2025.10.24 ~ 10.31",
    team: "5명",
    role: "RLHF 학습 파이프라인 설계 및 검증",
    tags: ["LLM", "RLHF", "Fine-tuning"],
    desc: "기존 QA 모델에 RLHF(인간 피드백 강화학습)를\n적용하여, 단순히 정확한 답이 아니라 사람이\n선호하는 자연스러운 답변을 하도록 튜닝했습니다.",
    overview: "SFT-RM-PPO 전 과정을 포함한 RLHF 파이프라인을 구축하여, 한국어 질의응답에서 인간 선호도에 더 부합하는 답변을 생성하도록 모델을 최적화했습니다.",
    features: [
      "Supervised Fine-Tuning (SFT)",
      "Reward Model (RM) 구축",
      "PPO 기반 강화학습 적용",
      "LLaMA 3.2 1B 모델 최적화"
    ],
    stack: ["Python", "Hugging Face", "LLaMA", "LoRA", "PPO"],
    performance: "RLHF 적용 전후 응답 품질 비교 실험 및 보상 모델 정확도 검증 완료",
    hasVideo: false,
    githubUrl: "https://github.com/kjw402540/RLHF_RAG-BASED-QA",
    imageUrl: "/qa_image.jpg",
  },
  {
    id: 4,
    abbr: "Urgency",
    color: "bg-red-900",
    badge: "AI CORE",
    title: "긴급도 판별",
    subtitle: "멀티모달 기반 긴급도 분류",
    date: "2025.10.17 ~ 10.24",
    team: "5명",
    role: "멀티모달 모델 구조 설계 및 실험",
    tags: ["Audio", "Multi-modal", "Wav2Vec2"],
    desc: "신고자의 음성(톤, 떨림)과 텍스트를\n복합적으로 분석하여 119 신고의 긴급도를\n 판별한 프로젝트입니다.",
    overview: "실제 119 신고 데이터의 음성과 텍스트를 활용해 긴급도(상·중·하) 분류를 시도했습니다. 단일 모달 입력과 멀티모달 입력 방식을 비교하며, 구조적 복잡성과 성능상의 한계를 확인하는 데 목적을 두었습니다",
    features: [
      "음성 데이터 전처리 및 특징 추출",
      "텍스트 기반 긴급도 분류 입력 구성",
      "멀티모달 퓨전 (Concatenate/Gate)",
      "긴급도/감정상태 상관관계 분석"
    ],
    stack: ["Python", "KoELECTRA", "Wav2Vec2", "Whisper"],
    performance: "음성-텍스트 결합 시 긴급도 분류 성능 변화 실험적 확인",
    hasVideo: false,
    githubUrl: "https://github.com/rloorrrr/UrgencyDetect",
    imageUrl: "/urgency_image.jpg",
  },
  {
    id: 5,
    abbr: "FlowerMap",
    color: "bg-pink-900",
    badge: "WEB",
    title: "꽃 피면\n알려줄 지도",
    subtitle: "벚꽃 명소 추천 지도 서비스",
    date: "2025.03.04 ~ 04.01",
    team: "5명",
    role: "전체 UI/UX 기획 및 프론트엔드 구현",
    tags: ["React", "Map API", "Planning"],
    desc: "지도 기반으로 벚꽃 명소를 소개하고 날씨 정보와 관광지 데이터를 활용하며, 챗봇과의 대화를 통해 그 외의 추천 정보를 확인할 수 있습니다",
    overview: "지도에서 지역을 선택하면 사전에 수집된 벚꽃 명소를 확인하고, 해당 장소의 기상 정보와 관광 정보를 함께 조회할 수 있는 벚꽃 명소 추천 서비스입니다. 챗봇을 통해 장소 관련 정보를 대화형으로 탐색할 수 있습니다.",
    features: [
      "지도 기반 벚꽃 명소 조회 기능",
      "장소별 기상 정보 및 관광 정보 제공",
      "챗봇을 활용한 벚꽃 명소 정보 추천",
      "반응형 웹 UI 구현"
    ],
    stack: ["JavaScript", "React.js", "Kakao Map API"],
    performance: "기획안을 실제 코드로 100% 구현하며 기획-개발 프로세스 정립",
    hasVideo: true,
    videoId: "kVt7anl6oiM?si=mePnKR63FmBKNDWl",
  },
  {
    id: 6,
    abbr: "SceneList",
    color: "bg-purple-900",
    badge: "TOOL",
    title: "씬 리스트 생성기",
    subtitle: "대본 자동 분석 및 씬 리스트 추출",
    date: "2024.12 ~ ",
    team: "1명 (개인 프로젝트)",
    role: "Python 로직 구현 및 GUI 개발",
    tags: ["Python", "Automation", "NLP"],
    desc: "드라마/영화 대본 파일을 업로드하면 AI가 씬 정보(장소, 시간, 등장인물)를 파싱하여 촬영 스케줄표용 데이터로 변환해주는 자동화 툴입니다.",
    overview: "영상 제작 프리프로덕션 단계에서 시간이 많이 소요되는 작업 중 하나인 '씬 리스트 작성'을 자동화한 툴입니다. 비정형 텍스트인 대본(PDF)을 분석하여 촬영에 필요한 메타데이터를 구조화된 엑셀 파일로 변환합니다.",
    features: [
      "씬 넘버 및 지문/대사 분리",
      "장소, 시간, 등장인물 자동 태깅",
      "촬영 스케줄링용 엑셀(XLSX) 파일 자동 생성",
      "사용자 편의를 위한 GUI 환경 제공"
    ],
    stack: ["Python", "Pandas", "PyQt5", "Regular Expression"],
    performance: "기존 수작업 대비 씬 리스트 정리 시간 80% 이상 단축",
    hasVideo: false,
    githubUrl: "https://github.com/5oran9/call-sheet-generator",
    imageUrl: "/scenelist_image.png",
  }
];